### PR TITLE
Switched from Maven to Gradle

### PR DESCRIPTION
**Pull request by johnzeringue**
Switched from Maven 3.x to Gradle 2.11.

### CODE REVIEW

**Comment by johnzeringue** [comment]
@bowring, you'll want to be careful that you don't commit `target/` after merging this as I've removed it from the `.gitignore`.

**Comment by bowring** [comment]
10.4

**Comment by bowring** [comment]
@johnzeringue: I am not up to speed on gradle.  The Maven setup produces a jar and a javadocs jar automatically.  How can we get this behavior with gradle?  Thanks. PS I see the GeoSamples.jar, but not the javadocs jar.  Also, how can we provide the jar naming with version number that Maven provides?

**Comment by johnzeringue** [comment]
Try gradle javadocJar and gradle jar.

**Comment by bowring** [comment]
cool; I see using version = 'x.y.z' solves the naming problem.

**Comment by johnzeringue** [comment]
What's the naming problem?

**Comment by johnzeringue** [comment]
Oh, sorry, I didn't see the edit in my inbox.

**Pull request closed without merging**
